/* Original reference implementation for this specification. No dependencies. */
(function(root){
'use strict';
const KEYS=['hp','spd','ea','pa','ed','pd'];
const STRONG={water:'fire',fire:'nature',nature:'water',earth:'lightning',wind:'earth',lightning:'wind'};
function integer(n,min,max,label){if(!Number.isSafeInteger(n)||n<min||n>max)throw new RangeError(label);return n;}
function finite(n,min,max,label){if(!Number.isFinite(n)||n<min||n>max)throw new RangeError(label);return n;}
function baseStat(rank,level,color,isHp=false){integer(rank,1,5,'rank');integer(level,1,35,'level');if(!['red','white','green'].includes(color))throw new TypeError('color');const c={red:1,white:2,green:3}[color];return Math.floor(((isHp?12:3)+2*rank+1.5*c)/(isHp?5:6)*level+(isHp?10:5));}
function totalStats(ranks,level,colors,bonuses,relics=[],temporary={}){const out={};for(const k of KEYS){const b=integer(bonuses[k],0,136,'bonus '+k);out[k]=baseStat(ranks[k],level,colors[k],k==='hp')+b+relics.reduce((s,r)=>s+finite(r.statModifiers[k]??0,-10000,10000,'relic'),0)+finite(temporary[k]??0,-10000,10000,'temporary');}return out;}
function elementMultiplier(attack,defenders,negate=false){if(!Object.keys(STRONG).includes(attack)&&attack!=='physical')throw new TypeError('attack element');if(!Array.isArray(defenders)||defenders.length<1||defenders.length>2||new Set(defenders).size!==defenders.length||defenders.some(e=>!STRONG[e]))throw new TypeError('defender elements');if(negate||attack==='physical')return 1;return defenders.reduce((m,d)=>m*(STRONG[attack]===d?2:STRONG[d]===attack?.5:1),1);}
function directDamage({ap,attack,defense,element='physical',defenderElements=['fire'],hits=1,hp,negate=false}){finite(ap,0,10000,'AP');finite(attack,1,100000,'attack');finite(defense,1,100000,'defense');integer(hits,1,100,'hits');finite(hp,1,100000,'HP');const multiplier=elementMultiplier(element,defenderElements,negate);const base=ap*attack/defense*multiplier;const perHitMin=Math.floor(base*.9),perHitMax=Math.floor(base*1.1);const min=perHitMin*hits,max=perHitMax*hits,midpoint=Math.floor((min+max)/2);return {modelId:'hub-direct-v1',base,perHitMin,perHitMax,min,max,midpoint,multiplier,koMinHits:max>0?Math.ceil(hp/max):null,koGuaranteedHits:min>0?Math.ceil(hp/min):null,usesByMidpoint:midpoint>0?Math.ceil(hp/midpoint):null,conditionalOn:'all hits land; no critical, status, shield or other special effects'};}
function seededRandom(seed){integer(seed,0,4294967295,'seed');let a=seed>>>0;return()=>{a=(a+0x6D2B79F5)>>>0;let t=a;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return ((t^(t>>>14))>>>0)/4294967296;};}
function checkedRandom(rng){const x=rng();if(!Number.isFinite(x)||x<0||x>=1)throw new RangeError('RNG must return [0,1)');return x;}
function rebonus(deprioritized=[],rng=Math.random){if(!Array.isArray(deprioritized)||deprioritized.length>5||new Set(deprioritized).size!==deprioritized.length||deprioritized.some(k=>!KEYS.includes(k)))throw new TypeError('deprioritized');const d=deprioritized.length,low=1/6-.02,high=d?(1-d*low)/(6-d):1/6;const weights=KEYS.map(k=>d&&deprioritized.includes(k)?low:high);const counts=KEYS.map(()=>0);for(let n=0;n<130;n++){const r=checkedRandom(rng);let cumulative=0,chosen=5;for(let i=0;i<6;i++){cumulative+=weights[i];if(r<=cumulative){chosen=i;break;}}counts[chosen]++;}const order=[0,1,2,3,4,5].sort((a,b)=>counts[a]-counts[b]||a-b);const excess=Math.max(0,counts[order[0]]+counts[order[1]]-32);if(excess){counts[order[1]]-=excess;for(let i=0;i<excess;i++)counts[order[2+Math.floor(checkedRandom(rng)*4)]]++;}return Object.fromEntries(KEYS.map((k,i)=>[k,counts[i]+1]));}
function rebonusPrice(current,deprioritizedCount){integer(deprioritizedCount,0,5,'deprioritized count');const total=KEYS.reduce((s,k)=>s+integer(current[k],0,136,'bonus'),0);integer(total,0,136,'total');return 136-total+[25,60,50,45,50,60][deprioritizedCount];}
function availableOn(schedule,date=new Date()){if(!(date instanceof Date)||!Number.isFinite(date.getTime()))throw new TypeError('date');if(!schedule||schedule.rule!=='weekly'||!Array.isArray(schedule.weekdays))return null;if(schedule.validFrom&&date<new Date(schedule.validFrom))return false;if(schedule.validUntil&&date>=new Date(schedule.validUntil))return false;const day=date.getUTCDay()||7;return schedule.weekdays.includes(day);}
function projectPoint(marker,imageRect,zoom=1,pan={x:0,y:0}){finite(marker.x,0,1,'x');finite(marker.y,0,1,'y');return {x:imageRect.x+pan.x+marker.x*imageRect.width*zoom,y:imageRect.y+pan.y+marker.y*imageRect.height*zoom};}
function wilson(successes,n){integer(n,1,100000000,'n');integer(successes,0,n,'successes');const z=1.959963984540054,p=successes/n,den=1+z*z/n,c=(p+z*z/(2*n))/den,h=z*Math.sqrt(p*(1-p)/n+z*z/(4*n*n))/den;return {p,low:Math.max(0,c-h),high:Math.min(1,c+h)};}
const api={KEYS,baseStat,totalStats,elementMultiplier,directDamage,seededRandom,rebonus,rebonusPrice,availableOn,projectPoint,wilson};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.MiscritsCore=api;
})(typeof globalThis==='undefined'?this:globalThis);
